godder:
  email:
    host:
    port:
    from:
    password:
    to:
  disk:
    name: my-server
    disk_unit: GB
    alert_threshold: 1
  sql:
    query_unit: s
    slow_query_time: 100
    databases:
      - name:
        type:
        host:
        port:
        user:
        password:
